### PR TITLE
add countdown to _index.md 

### PR DESCRIPTION
**Pull request by thommas-em**

### CODE REVIEW

**Review by flippette — CHANGES_REQUESTED** [review]
you might wanna add `.vscode` to `.gitignore`
otherwise lgtm

**Comment by thommas-em** [comment]
i dont really know how to do it, can you make some examples?

**Comment by flippette** [comment]
append this line to the `.gitignore` file

```
.vscode/
```

**Review by flippette — APPROVED** [review]
lgtm, i'll refactor separately

**Pull request merged**
